holdout_source: eyepacs
manifest_train: data/train/aptos_messidor2_ddr/manifest.csv
manifest_val: data/val/aptos_messidor2_ddr/manifest.csv
manifest_test: data/splits/lodo_unbalanced/lodo_eyepacs_test_full.csv